server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-holy-grass-aeniyjhl-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_GISH4LmYD2Xw
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: agri_sales_secret_key_1234567890_change_in_production
  expiration: 86400000 # 24 hours in milliseconds

file:
  upload-dir: uploads/
